name: v2
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: XipanXiao <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  angular: ^5.0.0
  angular_components: 0.12.0
  angular_forms: ^2.1.0

dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0
  pedantic: ^1.0.0
